name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [ ".", "elasticsearch", "mongo", "mssql", "mysql", "postgres" ]
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Setup
        uses: nhatthm/gh-actions/find-go-version@master

      - name: Install Go
        uses: nhatthm/gh-actions/setup-go@master
        with:
          go-version: ${{ env.GO_LATEST_VERSION }}

      - name: Lint
        uses: nhatthm/gh-actions/golangci-lint@master
        with:
          working-directory: ${{ matrix.module }}
