name: test

on:
  push:
    branches:
      - master
  pull_request:

env:
  GO111MODULE: "on"
  GO_LATEST_VERSION: "1.19.x"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.17.x, 1.18.x, 1.19.x ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go cache
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-cache

      - name: Test
        id: test
        run: |
          make test

      - name: Upload code coverage (integration)
        if: matrix.go-version == env.GO_LATEST_VERSION
        uses: codecov/codecov-action@v3
        with:
          files: ./features.coverprofile,elasticsearch/features.coverprofile,mongo/features.coverprofile,mssql/features.coverprofile,mysql/features.coverprofile,postgres/features.coverprofile
          flags: featurestests-${{ runner.os }}
